# Default values for auth-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

containerPort: 8083

image:
  repository: docker.io/seminariojalapa/auth-service
  tag: 'prod'
  pullPolicy: Always

ingress:
  enabled: true
  host: dev.one21.app
  tlsSecretName: auth-tls-secret

issuer:
  name: letsencrypt-prod
  email: jmarroquins13@miumg.edu.gt

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

service:
  annotations: {}
  type: ClusterIP
  port: 8083

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: "1"
  #   memory: "1Gi"
  requests:
    cpu: "30m"
    memory: "100Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

livenessProbe:
  tcpSocket:
    port: 8083
readinessProbe:
  tcpSocket:
    port: 8083
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 1
  successThreshold: 1
  initialDelaySeconds: 3
startupProbe:
  tcpSocket:
    port: 8083
  periodSeconds: 1
  timeoutSeconds: 3
  failureThreshold: 1
  successThreshold: 1
  initialDelaySeconds: 5

nodeSelector: {}

tolerations: []

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: auth-service

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: auth-service

securityContext:
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
    add:
      - SETPCAP
      - MKNOD
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - SYS_PTRACE

envVars:

generatorLabel: draft

keycloak:
  ingress:
    enabled: true
    host: dev-keycloak.one21.app
    tlsSecretName: keycloak-tls-secret
    certManagerClusterIssuer: letsencrypt-prod
  replicaCount: 1
  image:
    repository: quay.io/keycloak/keycloak
    tag: "23.0.6"
    pullPolicy: IfNotPresent
  containerPort: 8080
  secretName: keycloak-secret
  db:
    secretName: keycloak-secret
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: "30m"
      memory: "100Mi"
    # limits:
    #   cpu: "1"
    #   memory: "2Gi"
  livenessProbe:
    httpGet:
      path: /health/live
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health/ready
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /health/ready
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 60
  podSecurityContext: {}
  securityContext: {}
