# Default values for api-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

containerPort: 3000

image:
  repository: docker.io/seminariojalapa/api-gateway
  tag: 'prod'
  pullPolicy: Always

ingress:
  enabled: true
  host: one21.app
  tlsSecretName: gateway-tls-secret

issuer:
  name: letsencrypt-prod
  email: jmarroquins13@miumg.edu.gt

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

service:
  annotations: {}
  type: ClusterIP
  port: 3000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: "1"
  #   memory: "1Gi"
  requests:
    cpu: "30m"
    memory: "100Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

livenessProbe:
  tcpSocket:
    port: 3000
readinessProbe:
  tcpSocket:
    port: 3000
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 1
  successThreshold: 1
  initialDelaySeconds: 3
startupProbe:
  tcpSocket:
    port: 3000
  periodSeconds: 1
  timeoutSeconds: 3
  failureThreshold: 1
  successThreshold: 1
  initialDelaySeconds: 6

nodeSelector: {}

tolerations: []

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: api-gateway

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: api-gateway

securityContext:
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
    add:
      - SETPCAP
      - MKNOD
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - SYS_PTRACE

generatorLabel: draft

envVars:
  - name: AUTH_URL
    value: "http://auth-service.one21.svc.cluster.local:8083"
  - name: BUSINESS_PARTNERS_URL
    value: "http://one21-business-partners-service.one21.svc.cluster.local:9000"
  # - name: serviceGATEMASTERURL
  #   value: "http://auth-service.one21.svc.cluster.local:8083"

# Dragonfly Cache Configuration
dragonflycache:
  replicaCount: 1

  image:
    repository: docker.dragonflydb.io/dragonflydb/dragonfly
    tag: latest
    pullPolicy: IfNotPresent

  containerPort: 6379

  resources:
    requests:
      cpu: "30m"
      memory: "256Mi"

  livenessProbe:
    tcpSocket:
      port: 6379
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    tcpSocket:
      port: 6379
    initialDelaySeconds: 3
    periodSeconds: 5

  startupProbe: {}

  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""

  service:
    type: ClusterIP
    port: 6379

  auth:
    enabled: false             
    secretName: api-gateway-dragonfly-auth-secret
    secretKey: password
    autoCreate: false
    password: ""               
