apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}-keycloak
  labels:
    app: {{ include "auth-service.fullname" . }}-keycloak
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.keycloak.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "auth-service.fullname" . }}-keycloak
